name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  ci-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install PNPM using the official action
      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8.8.0  # or latest

      # Verify PNPM installation and version
      - name: Verify PNPM installation
        run: pnpm --version

      # Install dependencies using pnpm
      - name: Install Dependencies
        run: pnpm install

      # Run affected commands: lint, test, and build using Nx
      - name: Run Affected Commands
        run: pnpm nx affected --target=lint,test,build,e2e-ci